# https://bugs.gentoo.org/759685
dev-lang/python:3.9
